### ISSUE TITLE
Prettier plugin

### ISSUE THREAD

**Issue by v1rtl** [ezakto/qedit#1]
Hello, the project looks amazing, especially the plugin system!

I would like to recommend to add a [Prettier](https://prettier.io) plugin, it's the most popular code prettifier at the moment.

It has quite an easy to use [API](https://prettier.io/docs/en/api.html) so might worth checking :D

**Comment by ezakto** [comment]
I wonder how it'd work. Formatting while typing, on line breaks, or maybe with a dedicated shortcut like ctrl+enter?

**Comment by v1rtl** [comment]
@ezakto I think attaching it to Ctrl+S shortcut would make sense

but Ctrl+Enter sounds nice

**Comment by ezakto** [comment]
I went ahead and added a minimal plugins API and a prettier plugin with some customization options (all optional):

```js
Qedit.create(document.querySelector('.qedit'), {
  plugins: [QeditPrettier({
    trigger: 'ctrl+enter',
    formatOnInit: false,
    prettierOptions: { parser: 'babel' },
  })],
});
```

Hopefully it'll suit most needs. Thanks for the suggestion!

**Comment by v1rtl** [comment]
@ezakto looks very nice! thanks for taking time to make it
